"""empty message

Revision ID: b77056c840b8
Revises: 3372e77a73a9
Create Date: 2019-12-21 14:07:42.659716

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b77056c840b8'
down_revision = '3372e77a73a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('w_user', sa.Column('phone', sa.String(length=20), nullable=True, comment='用户手机号码'))
    op.alter_column('w_user', '_password',
               existing_type=mysql.VARCHAR(length=50),
               comment='用户密码',
               existing_nullable=False)
    op.alter_column('w_user', 'email',
               existing_type=mysql.VARCHAR(length=30),
               comment='用户邮箱',
               existing_nullable=True)
    op.alter_column('w_user', 'emp_no',
               existing_type=mysql.VARCHAR(length=30),
               comment='员工编号',
               existing_nullable=True)
    op.alter_column('w_user', 'permission',
               existing_type=mysql.INTEGER(display_width=11),
               comment='用户权限值',
               existing_nullable=True)
    op.alter_column('w_user', 'username',
               existing_type=mysql.VARCHAR(length=50),
               comment='用户名称',
               existing_nullable=False)
    op.create_unique_constraint(None, 'w_user', ['emp_no'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'w_user', type_='unique')
    op.alter_column('w_user', 'username',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='用户名称',
               existing_nullable=False)
    op.alter_column('w_user', 'permission',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='用户权限值',
               existing_nullable=True)
    op.alter_column('w_user', 'emp_no',
               existing_type=mysql.VARCHAR(length=30),
               comment=None,
               existing_comment='员工编号',
               existing_nullable=True)
    op.alter_column('w_user', 'email',
               existing_type=mysql.VARCHAR(length=30),
               comment=None,
               existing_comment='用户邮箱',
               existing_nullable=True)
    op.alter_column('w_user', '_password',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='用户密码',
               existing_nullable=False)
    op.drop_column('w_user', 'phone')
    # ### end Alembic commands ###
